# Rushy Panchal
# tasks/packages.yml
# Contains the package installation directives for Ansible

- name: install general packages
  apt: pkg={{ item }} state=installed
  with_items:
    - git
    - make
    - emacs
    - ufw # Server firewall
    - fail2ban # prevent brute-force SSH login attacks
    - vnstat # network usage monitoring
- name: install Python-development packages
  apt: pkg={{ item }} state=installed
  with_items: # needed for building various C-based Python packages
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - libffi-dev
    - python
    - python-pip
    - python-virtualenv
    - python-dev
- name: install web development libraries
  apt: pkg={{ item }} state=installed
  with_items:
    - nginx

# Python version management
- name: install pyenv
  git: repo=https://github.com/yyuu/pyenv.git dest="~{{ config.user.name }}/.pyenv" clone=yes
  become: yes
  become_user: "{{ config.user.name }}"
- name: install Python version(s)
  shell: source ~/.profile && pyenv install {{ config.app.py_version | quote }}
  args:
    executable: /bin/bash
    creates: "~/.pyenv/versions/{{ config.app.py_version }}"
  become: yes
  become_user: "{{ config.user.name }}"
