# Rushy Panchal
# tasks/directories.yml
# Contains the general setup directives for Ansible

# Configure UFW with firewall settings
- name: configure ufw firewall
  ufw: policy=reject state=enabled rule=allow port={{ item }} src=any
  with_items:
    - ssh
    - http
    - https
- name: ensure services are running
  service: name={{ item }} state=running
  with_items:
    - nginx
    - ssh
- name: allow services to be run by user
  lineinfile: dest=/etc/sudoers line={{ item }}
  with_items:
    - "{{ config.user.name }} ALL = (root) NOPASSWD: /usr/sbin/service"

- name: prevent SSH password authentication
  lineinfile: dest=/etc/ssh/sshd_config
    regexp="^PasswordAuthentication"
    line="PasswordAuthentication no"
    state=present
- name: prevent SSH root login
  lineinfile: dest=/etc/ssh/sshd_config
    regexp="^PermitRootLogin"
    line="PermitRootLogin no"
    state=present
- name: restart SSH
  service: name=ssh state=restarted
