# Rushy Panchal
# server.yml
# Ansible playbook for setting up the server

---

- hosts: localhost
  remote_user: ubuntu
  become_user: 'sudo_user'
  tasks:
    # import configuration variables
    # all variables are subscripted with "default"
    - include_vars: config.yml
    - include: tasks/users.yml
    - include: tasks/packages.yml
    - include: tasks/directories.yml
    - include: tasks/setup.yml
