# Rushy Panchal
# tasks/directories.yml
# Contains the directory creation directives for Ansible

- name: create web directory
  action: file path=/var/www/ state=directory group={{ config.user.name }} owner={{ config.user.name }}
- name: create other directories
  action: file path={{ item }} state=directory group={{ config.user.name }} owner={{ config.user.name }}
  with_items:
    - /var/www/{{ config.web.url }} # web directory
    - /var/repo/{{ config.name }}.git # repository directory
    - /var/cache/nginx # NginX cache directory
    - /etc/nginx/ssl/{{ config.web.url }} # NginX ssl configuration
    - /var/log/{{ config.name }} # Service logs directory
