# Rushy Panchal
# tasks/directories.yml
# Contains the general setup directives for Ansible

# Configure UFW with firewall settings
- name: configure ufw firewall
  action: ufw policy=reject state=enabled rule=allow port={{ item }} src=any
  with_items:
    - ssh
    - http
    - https
- name: ensure services are running
  action: service name={{ item }} state=running
  with_items:
    - nginx
    - ssh
  