#---------------------------------------------------------------------
# Makefile
# Author: Yuan Wang
# Copyright Jellifish 2015
#---------------------------------------------------------------------

test:
	python testTaskNode.py

clean_py:
	rm -f *.py~
